#define IDH_ALL_DIALOGS 2
#define IDH_HRMSystem_Form_ChangePassword  10
#define IDH_HRMSystem_Form_CompanyInfo  110
#define IDH_HRMSystem_Form_CustomFields  600
#define IDH_HRMSystem_Form_Default  720
#define IDH_HRMSystem_Form_Email_Notification  760
#define IDH_HRMSystem_Form_Employee  910
#define IDH_HRMSystem_Form_Help  2170
#define IDH_HRMSystem_Form_Import_Export  2210
#define IDH_HRMSystem_Form_Job  2640
#define IDH_HRMSystem_Form_Login  3430
#define IDH_HRMSystem_Form_Logout  3490
#define IDH_HRMSystem_Form_Membership  3500
#define IDH_HRMSystem_Form_Nationaity_Race  3770
#define IDH_HRMSystem_Form_ProjectInfo  4030
#define IDH_HRMSystem_Form_Qualification  4400
#define IDH_HRMSystem_Form_Recruitment  4670
#define IDH_HRMSystem_Form_Skills  4870
#define IDH_HRMSystem_Form_Users  5140

